In [8]:
import numpy as np
matriu = np.array([[1, 2, 1], [6, 4, 5]])
matriu
ind = np.argmin(matriu[0])
ind

0

In [14]:
def expected_points(nVerd, nVerm):
    if nVerd == 0:
        return 0
    if nVerd - nVerm > 0:
        return 1
    else:
        return nVerm/(nVerd+nVerm)*expected_points(nVerd, nVerm-1) + nVerd/(nVerd+nVerm)* expected_points(nVerd-1, nVerm)
    
    
    

In [17]:
expected_points(4,4)

0.8

In [38]:
def superior_neighbors(mat, point):
    """
    Donada una matriu de mida H x W i punt, retorna els punts de la fila superior adjacents al punt passat com a paràmetre.
    Cal tenir en compte els següents casos. Considerant que el punt té coordenades (i,j):
        - Si el punt té coordenada j=0, vol dir que estem agafant un punt del marge esquerre de la imatge. Només s'han de retornar DOS veïns.
        - Si el punt té coordenada j=(W-1), vol dir que estem agafant un punt del marge dret de la imatge. Només s'han de retornar DOS veïns.
        - En la resta de casos, es retornen els tres veïns superiors.
        
    Params
    ======
    :mat: Una matriu 2-Dimensional
    :point: Un sol punt amb el format (i,j)
    
    Returns
    =======
    :neighbors: Una llista de dos o tres elements en funció de cada cas.
    """
    list_neighbors = []
    i = point[0]
    j = point[1]
    if i < mat.shape[0] and j < mat.shape[1]:
        if i != 0:
            if j == 0:
                list_neighbors.append((i-1,j))
                list_neighbors.append((i-1,j+1))
            elif j == mat.shape[1] - 1:
                list_neighbors.append((i-1,j-1))
                list_neighbors.append((i-1,j))
            else:
                list_neighbors.append((i-1,j-1))
                list_neighbors.append((i-1,j))
                list_neighbors.append((i-1,j+1))
        
    neighbors = np.array(list_neighbors)
    return neighbors

        
mat=np.array([[1,2,3, 4, 5, 7], [2,23,5, 8, 9, 1], [5,3,4, 2, 2, 2]])
val=superior_neighbors(mat, (2,3))
val

array([[1, 2],
       [1, 3],
       [1, 4]])

In [51]:
a = np.array([[1,2],[3,4]])
a[a[:,:]<3] = 0
a

array([[0, 0],
       [3, 4]])

In [45]:
existing_array = np.array([], dtype=object)

# Tuple to append
# Append the tuple to the existing array
new_array = np.append(existing_array, [(1,2)])
new_array = np.append(new_array, [(3,4)])

print(new_array)

[1 2 3 4]


In [46]:
array_de_tuplas = np.array([], dtype=object)

# Tuples to append
new_tuples = [(1, 2), (3, 4), (5, 6)]

# Append each tuple to the array
for new_tuple in new_tuples:
    array_de_tuplas = np.append(array_de_tuplas, [new_tuple], axis=0)

print(array_de_tuplas)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [30]:
list_de_tuplas = []

# Tuples to append
new_tuples = [(1, 2), (3, 4), (5, 6)]

# Append each tuple to the list
for new_tuple in new_tuples:
    list_de_tuplas.append(new_tuple)

# Convert the list to a NumPy array
array_de_tuplas = np.array([], dtype=object)

print(np.any(array_de_tuplas))

False


In [27]:
a = np.array([[1,2,2,1],[1,3,4,5]])
b = np.where(a[0] == 2)
b[0]

array([1, 2])

In [26]:
import numpy as np

# Example 1-dimensional NumPy array
my_array = np.array([10, 20, 30, 40, 50])
target_value = 30

# Find the index where the target value occurs in the array
indices = np.where(my_array == target_value)
print(indices)
# Print the result
if indices[0].size > 0:
    print("Index of", target_value, ":", indices[0][0])
else:
    print(target_value, "not found in the array.")

(array([2]),)
Index of 30 : 2


In [ ]:
def superior_neighbors(mat, point):
    """
    Donada una matriu de mida H x W i punt, retorna els punts de la fila superior adjacents al punt passat com a paràmetre.
    Cal tenir en compte els següents casos. Considerant que el punt té coordenades (i,j):
        - Si el punt té coordenada j=0, vol dir que estem agafant un punt del marge esquerre de la imatge. Només s'han de retornar DOS veïns.
        - Si el punt té coordenada j=(W-1), vol dir que estem agafant un punt del marge dret de la imatge. Només s'han de retornar DOS veïns.
        - En la resta de casos, es retornen els tres veïns superiors.
        
    Params
    ======
    :mat: Una matriu 2-Dimensional
    :point: Un sol punt amb el format (i,j)
    
    Returns
    =======
    :neighbors: Una llista de dos o tres elements en funció de cada cas.
    """
    list_neighbors = []
    i = point[0]
    j = point[1]
    if i < mat.shape[0] and j < mat.shape[1]:
        if i != 0:
            if j == 0:
                list_neighbors.append(mat[i-1][j])
                list_neighbors.append(mat[i-1][j+1])
            elif j == mat.shape[1] - 1:
                list_neighbors.append(mat[i-1][j-1])
                list_neighbors.append(mat[i-1][j])
            else:
                list_neighbors.append(mat[i-1][j-1])
                list_neighbors.append(mat[i-1][j])
                list_neighbors.append(mat[i-1][j+1])
        
    neighbors = np.array(list_neighbors)
    return neighbors


def minimal_paths(mat):
    """
    Creació de tots els camins mínims usant programació dinàmica.
    Cal usar la funció 'superior_neighbors' per trobar els veïns.
    
    Params
    ======
    :mat: Matriu 2-Dimensional d'entrada (gradient)
    
    Returns
    =======
    :ret: Matriu 2-Dimensional de la mateixa mida que 'mat' amb els camins mínims calculats.
    """
    
    ret = mat.copy()
    
    H = mat.shape[0]
    W = mat.shape[1]
    for i in range(H):
        for j in range(W):
            neighbors = superior_neighbors(mat, (i,j))
            if np.any(neighbors):
                ret += min(neighbors)
    return ret


def find_min_path(mat):
    """
    Donada una matriu, calcula el camí mínim sobre aquesta. L'algorisme ha de començar per la part inferior i buscar el següents punts.
    
    Params
    ======
    :mat: Matriu de camins mínims
    
    Returns
    =======
    :min_path: Una llista de tuples amb les coordenades (i,j) del camí mínim. La primera coordenada ha d'anar decrementant sempre en 1.
               Exemple. Suposant que una imatge té d'alçada 341 píxels, un possible camí seria: [(340, 120), (339, 121), (338,120), ..., (0, 151)] 
    """
    
    
    H = mat.shape[0]
    W = mat.shape[1]
    
    min_path = []
    
    minimal_total_gradient_bottom = min(mat[H-1]) #Busquem el valor de gradient acumulat minim de la ultima fila
    possible_min_values = np.where(mat[H-1] == minimal_total_gradient_bottom)[0] #Busquem el index d'aquest valor i posem un [0] ja que pot ser que més d'un element de la úñtima fila tingui el mateix gradient minim acumulat, prenem el primer valor que ens retorna (arbitrari)
    min_path.append((H-1, possible_min_values[0]))
    for i in range(1, H):
        print(min_path)
        minimal_neig_value = min(superior_neighbors(mat, min_path[-1]))
        poss_min_values = np.where(mat[H-i] == minimal_neig_value)[0]
        min_path.append((H-i, poss_min_values[0]))
    
    
    return min_path



def delete_path(im, path):
    """
    Donat una imatge i un camí, elimina els pixels de la imatge que pertanyen del camí.
    Podeu usar la següent instrucció per inicialitzar la imatge. Això crea una imatge amb tots els valors a zero.
    
    im_new = np.zeros((im.shape[0], im.shape[1]-1, im.shape[2]))
    
    Params
    ======
    :im: Una imatge de mida H x W x 3
    :path: Un camí sobre la imatge. 
    
    Returns
    =======
    :im_new: Una nova imatge de mida H x (W-1) x 3 amb el camí eliminat
    """
    
    im_new = np.zeros((im.shape[0], im.shape[1]-1, im.shape[2]))
                        
    for k in range(im.shape[2]):
        for i in range(im.shape[0]):
            for j in range(im.shape[1]):
                if j < path[im.shape[0]-i][1]: #Comparem el valor de la columna amb el valor de la columna de l'index que està guardat al path per aquesta fila, recordem que els hem guardat en ordre ascendent, per això accedim d'aquesta manera
                    im_new[i][j][k] = im[i][j][k]
                elif j > path[im.shape[0]-i][1]:
                    im_new[i][j-1][k] = im[i][j][k]
    
    return im_new


def reduce_image(im, N=100):    
    """
    Implementació de l'algorisme Seam Carving. 
    Useu la funció 'show_row' al finalitzar per mostrar una figura amb tres subfigures:
        - Imatge original
        - Primer camí que s'elimina
        - Imatge resultant després de N iteracions
    
    Params
    ======
    :im: Imatge que volem reduir
    :N: Nombre de cops que repetirem l'algorisme
    """
    gradient = get_gradient(im)
    all_min_paths = minimal_paths(gradient)
    minimal_path = find_min_path(all_min_paths)
    im_path = im.copy()
    im_path = add_min_path(im_path, minimal_path)
    # Usem la funció show_row per mostrar les imatges amb els seus títols.
    im_titles = [(im, 'Original'), (im_path, 'Minimal path')]
    show_row(im_titles)
    
    im_new = delete_path(im, minimal_path)
                           
    pass