In [123]:
def satisfies(grid, x, y, num, top, bottom, left, right):
    """
    Donat un tauler, un punt amb coordenades (x,y) i un nombre 'num', comprova si és possible assignar-lo a la posició (x,y) 
    donades les restriccions del problema.
    
    Params
    ------
    :grid: Una matriu de numpy
    :x,y: Un punt de la matriu on volem posar el nombre 'num'
    :num: Un nombre enter
    :top, bottom, left, right: Els nombres de fora del tauler de la part superior, inferior, esquerra i dreta, respectivament.
    
    Returns
    -------
    :b: Un boleà True/False depenent de si el nombre 'num' pot ser col·locat a la casella (x,y) o no.
    """
    #Contem caselles plenes que compitn edificis vists des de la restricció
    comp = [0,0,0,0]
    
    if top[x-1] != 0:
        for i in range(y, len(left)):
            if grid[i][x-1] != 0:
                if grid[i][x-1] < num:
                    comp[0] += 1
                    
    if bottom[x-1] != 0:
        dim = len(left)
        for i in range(len(left)-y, len(left)):
            if grid[dim-1-i][x-1] != 0:
                if grid[dim-1-i][x-1] < num:
                    comp[2] += 1
                
    """last_val = -1
    if left[y-1] != 0:
        for j in range(len(top)):
            if grid[y-1][j] == 0:
                break
            if grid[y-1][j] > last_val:
                comp[1] += 1
                last_val = grid[y-1][j]"""
                
    """highest_val = -1
    if bottom[x-1] != 0:
        for i in range(dim):
            print(grid[dim-1-i][x-1])
            if grid[dim-1-i][x-1] != 0:
                if grid[dim-1-i][x-1] > highest_val:
                    comp[2] += 1
                    highest_val = grid[dim-1-i][x-1]"""
                
    """last_val = -1
    if right[y-1] != 0:
        dim = len(top)
        for j in range(len(top)):
            if grid[y-1][dim-1-j] == 0:
                break
            if grid[y-1][dim-1-j] > last_val:
                comp[3] += 1
                last_val = grid[y-1][dim-1-j]"""
    print(comp)
    #Avaluem si es pot posar el nou numero o no
    #Comencem mirant la restricció top
   
    """if top[x-1] != 0:
        restriction = top[x-1]
        if comp[0] >= restriction:
            pass
        elif y-1 == 0:
            if len(left) - num >= restriction - comp[0]:
                pass
            else:
                return False
        elif num >= grid[y-2][x-1]:
            if len(left) - num >= restriction - comp[0]:
                pass
            else:
                return False
        elif len(left)-y >= restriction - comp[0]:
            pass
        else:
            return False"""
    if top[x-1] != 0:
        restriction = top[x-1]
        if num > y - comp[0] and y < restriction:
            print("hola1")
            return False
        elif restriction - num + comp[0] > len(left) - y:
            print("hola2")
            return False
    
    if bottom[x-1] != 0:
        restriction = bottom[x-1]
        if num > len(left)-y+1-comp[2] and len(left)-y+1 < restriction:
            print(len(left))
            print(y)
            print(comp[2])
            print( len(left)-y+1 - comp[2])
            print("hola3")
            return False
        elif restriction - num + comp[2] > len(left) - y:
            print("hola4")
            return False
        
    """if bottom[x-1] != 0:
        restriction = bottom[x-1]
        if comp[2] >= restriction:
            pass
        elif y-1 == len(left):
            if len(left) - num >= restriction - comp[2]:
                pass
            else:
                return False
        elif num >= grid[y][x-1]:
            if len(left) - num >= restriction - comp[2]:
                pass
            else:
                return False
        elif y-1 >= restriction - comp[2]:
            pass
        else:
            return False"""
            
    
    return True

In [ ]:
def satisfies(grid, x, y, num, top, bottom, left, right):
    
    #top
    if len(left) - num < 
    
    comp = [0,0,0,0]
    max_val = -1
    if top[x-1] != 0:
        size = len(left)
        for i in range(size):
            if i < y-1: #Cas que estas entre observador i posicio on vols afegir
                if grid[i][x-1] > max_val:
                    comp[0] += 1
                    
                    potential_front[0] += 1
                elif 
                    
            if grid[i][x-1] == 0:
                potential_back += 1
            elif grid[i][x-1] > num:
                    comp[0] += 1

In [124]:
import numpy as np
from IPython.display import clear_output
import time
grid = np.zeros((4, 4), dtype='int')
grid[0] = [2,3,1,4]
grid[1] = [1,4,2,3]
grid[2] = [3,1,4,2]
grid[3] = [4,2,0,1]

print(grid)
satisfies(grid, 3, 4, 3, [0,0,3,0], [0,2,2,0], [0,0,0,0], [0,0,0,0])

[[2 3 1 4]
 [1 4 2 3]
 [3 1 4 2]
 [4 2 0 1]]
[0, 0, 2, 0]
4
4
2
-1
hola3


False

In [ ]:
    comp = [0,0,0,0]
    last_val = -1
    if top[x-1] != 0:
        for i in range(len(left)):
            if grid[i][x-1] == 0:
                break
            if grid[i][x-1] > last_val:
                comp[0] += 1
                last_val = grid[i][x-1]
                
    last_val = -1
    if left[y-1] != 0:
        for j in range(len(top)):
            if grid[y-1][j] == 0:
                break
            if grid[y-1][j] > last_val:
                comp[1] += 1
                last_val = grid[y-1][j]
                
    last_val = -1
    if bottom[x-1] != 0:
        dim = len(left)
        for i in range(dim):
            if grid[dim-1-i][x-1] == 0:
                break
            if grid[dim-1-i][x-1] > last_val:
                comp[2] += 1
                last_val = grid[dim-1-i][x-1]
                
    last_val = -1
    if right[y-1] != 0:
        dim = len(top)
        for j in range(len(top)):
            if grid[y-1][dim-1-j] == 0:
                break
            if grid[y-1][dim-1-j] > last_val:
                comp[3] += 1
                last_val = grid[y-1][dim-1-j]