<div style="padding:30px; color: white; background-color: #0071CD">
<center>
<img src="img/logoub.jpeg"></img>
<center>
<h1>Algorísmica Avançada</h1>
<h2>Problemes 9 - Enumeratius: Ramificació i Poda</h2>
</center>
</div>

In [6]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [7]:
import numpy as np
from queue import PriorityQueue

<div class="alert alert-success">
    <h1>Problema 1: Job Sequencing with deadlines</h1>
    <br> Suposem que tenim un conjunt de tasques a realitzar, $J_1,\dots,J_n$. Cada una d'elles té assignada una penalització per no realitzar-la a temps $p_1,\dots,p_n$, un temps de durada de la tasca $t_1,\dots,t_n$ i un temps de deadline: $d_1,\dots,d_n$.<br><br>
    Implementeu un algoritme que trobi quines tasques hem de realitzar i quines no per a tenir una penalització mínima. La funció ha de retornar les tasques realitzades i la penalització mínima obtinguda (la suma de les tasques que descartem).
    <br>
</div>

Un exemple concret:

| Tasca (Ji)  | 1 | 2 | 3 | 4 | 
| --- | --- | --- | --- | --- |
| Penalització  | 5 | 10 | 6 | 3 | 
| Deadline  | 1 | 3 | 2 | 1 | 
| Temps  | 1 | 2 | 1 | 1 | 

Considerem la notació següent:

Sigui $x$ un node, $S_x$ les tasques agafades en el node $x$:

$$m(x) = \max\{i\ |\ i\in S_x\} \ \ \ \ \ \ \text{És l'última tasca que forma part de la solució}$$
<br>
$$s(x) = \sum_{i\in S_x}t_i \ \ \ \ \ \ \text{És la suma dels temps que tardem a fer les tasques selecionades}$$
<br>
$$d(x) = \max\{d_i\ |\ i\in S_x\} \ \ \ \ \ \ \text{És el deadline màxim de les tasques que formen part de la solució}$$
<br>
$$c(x) = \sum_{i<m,\ i\notin S_x}p_i\ \ \ \ \ \ \text{És el cost de no considerar un seguit de tasques}$$
<br>
$$u(x) = \sum_{i\notin S_x}p_i \ \ \ \ \ \ \text{És la cota superior de les penalitzacions}$$
<br>
$$sup = \infty \ \ \ \ \ \ \text{Aquí guardarem la millor cota trobada fins al moment} $$

Anem a resoldre el problema. A l'acabar, ens ha de quedar un arbre com el següent:

<center><img src="img/tree.png" width='50%'/></center>

Acabeu d'omplir la següent taula d'execució:

| Node  | S_x | m(x) | s(x) | d(x) | c(x) | u(x) | sup |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 1 | {} | - | 0 | 0 | 0 | 5+10+6+3=24 | 24 |
| 2 | {1} | 1 | 1 | 1 | 0 | 10+6+3=19 | 19 |
| 3 |  |  |  | |  | | |
| 4 |  |  |  | |  | | |
| 5 |  |  |  | |  | | |
| 6 |  |  |  | |  | | |
| 7 |  |  |  | |  | | |
| 8 |  |  |  | |  | | |
| 9 |  |  |  | |  | | |
| 10 |  |  |  | |  | | |

Un parell de coses a considerar durant la implementació:
+ Us recomanem guardar 6 variables a la PriorityQueue: $c(x)$, $u(x)$, $S_x$, $s(x)$, $d(x)$ i $m(x)$. Extraureu sempre el node amb cost més baix.
+ A part de considerar les cotes $c(x)$ i $sup$ a l'hora d'afegir un nou node a la PQ, heu de controlar també els temps/deadlines. Una forma fàcil és comprovar que la suma de totes les tasques de la solució $s(x)$ és menor o igual al valor $d(x)$.

In [3]:
def compute_c(jobs, m, Sx):
    """
    Donada la llista de tasques, el valor m i les tasques seleccionades, calcula el valor c(x)
    """
    c = 0
    return c

def compute_u(jobs, Sx):
    """
    Donada la llista de tasques i les tasques seleccionades, calcula el valor u(x)
    """
    u = 0
    return u

def solve_jobs(jobs):
    """
    Soluciona el problema de les tasques
    """
    
    # Millor solució trobada. Inicialment té cota infinit
    sup = np.inf
    best_Sx = None
    
    # Guardem en una cua de prioritat els nodes
    # Guardarem les variables:
    # 1. Cost, c(x)
    # 2. Cota superior, u(x)
    # 3. Tasques que hem agafat fins al moment, S_x 
    # 4. Suma dels temps de les tasques de S_x, s(x)
    # 5. Màxim dels deadlines de les tasques de S_x, d(x)
    # 6. Valor m(x)
    
    # Inicialitzem la cua de prioritat i els diferents valors que guardarem
    pq = PriorityQueue()
    Sx = set()
    m = 0
    s = 0
    d = 0
    c = compute_c(jobs, m, Sx)
    u = compute_u(jobs, Sx)
    
    pq.put((c, u, Sx, s, d, m))
    
    while not pq.empty():
        
        # Obtenim un nou element de la cua, el de més baix cost
        current_c, current_u, current_Sx, current_sum, current_d, current_m = pq.get()        
    
        # EL TEU CODI AQUÍ
        
    return best_Sx, sup

In [4]:
# Retorna ({1, 2}, 0)
jobs = [(1, 10, 3, 2),
        (2, 3, 1, 1)]
solve_jobs(jobs)

(None, inf)

In [5]:
# Retorna ({2, 3}, 8)
jobs = [(1, 5, 1, 1),
        (2, 10, 3, 2),
        (3, 6, 2, 1),
        (4, 3, 1, 1)]
solve_jobs(jobs)

(None, inf)

<div class="alert alert-success">
    <h1>Problema 2: Sliding-Puzzle</h1>
    <br>
    Donat un taulell de $n\times n$ de nombres des d'$1$ fins a $n^2-1$ inicialment desordenats, volem trobar el nombre mínim de moviments possibles de manera que els nombres estiguin ordenats en ordre creixent i la casella sense número estigui a l'última posició.
</div>

<img src="https://www.researchgate.net/profile/Ruo-Ando/publication/347300656/figure/fig1/AS:969204928901121@1608087870493/Initial-state-and-goal-state-of-8-puzzle.ppm" width='50%'/>

In [3]:
from npuzzle import NPuzzle

# Inicialitzem un tauler i el barregem
board = NPuzzle()
board.create_board(n=3, moves=100)

print ("Un tauler aleatori:")
print(board)

Un tauler aleatori:
+-----------+
| 2 | 4 | 7 | 
+-----------+
| 6 | 8 | 5 | 
+-----------+
|   | 3 | 1 | 
+-----------+



La funció ``get_state_id`` ens retorna un 'string' amb la configuració del tauler. D'aquesta forma podrem guardar els estats que ja hem visitat per a no repetir-los


In [7]:
board.get_state_id()

'1,5,2,8,0,3,4,7,6'

Per a cada tauler, podem definir una cota que depèn del nombre de moviments que hem fet fins al moment i un valor optimista calculat com una 'distància' entre el tauler que estem considerant i el tauler objectiu.

$$C(X) = g(X) + h(X)$$
+ $g(X)$ és el nombre de passos que portem fins el moment.
+ $h(X)$ pot ser:
    + $h_1(X)$: El nombre de caselles que no estan al seu lloc sense tenir en compte la casella buida (hamming_distance)
    + $h_2(X)$: La suma de les distàncies de manhattan de cada casella al seu lloc correcte (manhattan_distance)

In [8]:
board.hamming_distance() # h1(X)

7

In [9]:
board.manhattan_distance() # h2(X)

8

Podem demanar quins moviments són valids des d'una configuració del tauler amb la funció ``allowed_moves()``. Un moviment consisteix en 'moure' la casella buida en una de les quatre direccions permeses:<br>
+ $L$: Left
+ $R$: Right
+ $U$: Up
+ $D$: Down

In [10]:
am = board.allowed_moves()
print(am)

['L', 'R', 'U', 'D']


Executem un moviment amb la funció ``move()``

In [11]:
new_board = board.move(am[0])
print(new_board)

+-----------+
| 1 | 5 | 2 | 
+-----------+
|   | 8 | 3 | 
+-----------+
| 4 | 7 | 6 | 
+-----------+



La funció state ens comprova si el nostre estat és un estat solució.

In [12]:
# Solucionat: True
# No solucionat: False
new_board.state()

False

In [10]:
def solve_puzzle(board):
    """
    Soluciona el problema del N-Puzzle
    
    Params
    ======
    :board: Un objecte de la classe NPuzzle
    
    Returns
    =======
    :best_bound: Nombre de passos mínims per transformar el tauler d'entrada en el tauler objectiu
    :best_board: El tauler objectiu. Haurien de ser els números ordenats de petit a gran amb la casella buida al final.
    :expanded: El nombre de taulers expandits. Cada cop que traiem un tauler de la cua de prioritat, sumem 1.
    """
    
    # Millor solució trobada. Inicialment té cota infinit
    best_bound = np.inf
    best_board = board
    
    # Guardem en una cua de prioritat els taulells.
    # Guardarem les variables:
    # 1. Distància mínima (cota inferior) entre el tauler actual i el tauler solució
    # 2. Número de passes que duem en aquest tauler, g(X)
    # 3. El tauler
    #La cua ens serveix per sempre fer cerca en el taular amb millors condicions
    pq = PriorityQueue()
    # Afegim a la cua el que hi ha ara mateix, cota inf, nombre de passes que portem i tauler
    pq.put((board.manhattan_distance(), 0, board))
    
    # Com que els estats poden repetir-se al llarg de l'exploració, guardarem en un 'set' tots els
    # estats visitats. Així evidem tornar a visitar estats.
    existent_states = set([board.get_state_id()])
    #  El nombre de taulers expandits. Cada cop que traiem un tauler de la cua de prioritat, sumem 1
    expanded = 0
    
    while not pq.empty():
        
        # Obtenim un nou element de la cua
        curr_bound, curr_steps, curr_board = pq.get()
        
        # EL TEU CODI AQUÍ
        for move in curr_board.allowed_moves():
            new_board = board.move(move)
            if new_board.state():
                return curr_steps+1, new_board, expanded
            pq.put((curr_steps+curr_board.manhattan_distance(), curr_steps+1, new_board))
                
    return best_bound, best_board, expanded
    

In [11]:
board = NPuzzle()
board.create_board(moves=100, n=3)
print("Tauler inicial:")
print(board)
distance, final_board, expanded = solve_puzzle(board)
print(f"Solucionat en {distance} passos")
print(f"Taulers expandits: {expanded}")
print("Tauler final:")
print(final_board)

Tauler inicial:
+-----------+
|   | 2 | 4 | 
+-----------+
| 8 | 6 | 3 | 
+-----------+
| 1 | 5 | 7 | 
+-----------+



KeyboardInterrupt: 

<div class="alert alert-success">    
    <h1>Problema 3: Assignació de tasques</h1>
    <br>
    Sigui $A$ una matriu de nombres enters de mida $n\times n$:
    $$A = \begin{pmatrix}a_{0,0}\quad \cdots \quad a_{0,n}\\
                         \vdots\quad\quad\quad\quad\vdots\\
                         a_{n,0}\quad \cdots \quad a_{n,n}
         \end{pmatrix}$$
    L'element $a_{i,j}$ correspon al cost d'assignar la tasca $i$ a l'empresa $j$.<br>
    Volem trobar el mínim cost d'assignar tasques a empreses amb la condició que totes les tasques han d'estar assignades i les empreses han de fer només una tasca.
     
</div>

## Funcions útils

In [15]:
costs = np.array([[11,12,18,40],
                  [14,15,13,22],
                  [11,17,19,23],
                  [17,14,20,28]])

####  <u>np.min</u>
Ens permet obtenir el mínim de cada columna o fila d'una matriu

In [16]:
print(costs.min(axis=0)) # Axis=0 indica que volem el mínim de cada columna
print(sum(costs.min(axis=0)))

[11 12 13 22]
58


In [17]:
print(costs.min(axis=1)) # Axis=1 indica que volem el mínim de cada fila
print(sum(costs.min(axis=1)))

[11 13 11 14]
49


#### <u>np.delete</u>
Ens permet eliminar una fila o una columna d'un array de numpy.<br>
Observa els exemples:

In [18]:
# Axis=0 indica que volem eliminar files. En aquest cas estem eliminant només la fila 2
new_costs1 = np.delete(costs, 2, axis=0) 
print(new_costs1)

[[11 12 18 40]
 [14 15 13 22]
 [17 14 20 28]]


In [19]:
# Axis=0 indica que volem eliminar files. En aquest cas estem eliminant les files 0 i 1
new_costs2 = np.delete(costs, [0,1], axis=0) 
print(new_costs2)

[[11 17 19 23]
 [17 14 20 28]]


In [20]:
# Axis=1 indica que volem eliminar columnes. En aquest cas estem eliminant les columnes 0 i 2
new_costs3 = np.delete(costs, [0,2], axis=1)
print(new_costs3)

[[12 40]
 [15 22]
 [17 23]
 [14 28]]


In [21]:
# Podem esborrar files i columnes d'una matriu
new_costs4 = np.delete(np.delete(costs, [0,1], axis=0), [2,3], axis=1)
print(new_costs4)

[[11 17]
 [17 14]]


In [22]:
def inf_bound(matrix):
    """
    Calcula la suma del mínim de cada columna
    
    Params
    ======
    :matrix: La matriu de costs
    
    Returns
    =======
    :inf: La suma del mínim de cada columna
    """
    
    return 0

def sup_bound(matrix):
    """
    Retorna el cost d'una assignació qualsevol.
    
    Params
    ======
    :matrix: La matriu de costs
    
    Returns
    =======
    :sup: El cost d'una assignació qualsevol. Per exemple, podem retornar la suma de la diagonal de la matriu
          que consisteix en assignar la tasca 'i' a l'empresa 'i' on i=0,1,2,3,4...
    """
    
    return 0

def tasks(matrix):
    """
    Troba l'assignació entre tasques i empreses amb cost mínim utilitzant ramificació i poda.
    Cada cop que troba una assignació millor ll'imprimeix per pantalla.
    
    Params
    =====
    :matrix: La matriu de costs
    """
    
    # Cotes inicials
    sup = sup_bound(matrix)
    inf = inf_bound(matrix)
    
    # Cua de prioritat. Guardarem quatre elements:
    # 1. Prioritat
    # 2. Parelles ja assignades (tasca, empresa)
    # 3. Tasca que hem d'assignar a continuació (row)
    # 4. Empreses ja assignades (col)
    pq = PriorityQueue()
    pq.put((inf, [], 0, set([])))
    
    # Iterarem mentre la cua de prioritat no sigui buida
    while not pq.empty():
        
        # Extraiem un element
        elem_cota, elem_list, elem_row, elem_cols = pq.get()  
        
        # EL TEU CODI AQUÍ
        

In [23]:
costs = np.array([[11,12,18,40],
                  [14,15,13,22],
                  [11,17,19,23],
                  [17,14,20,28]])

print("Matriu de costs:")
print(costs)
print()

# Millor solució trobada, cost: 61
# Tasca 0 -> Empresa 0
# Tasca 1 -> Empresa 2
# Tasca 2 -> Empresa 3
# Tasca 3 -> Empresa 1

tasks(costs)

Matriu de costs:
[[11 12 18 40]
 [14 15 13 22]
 [11 17 19 23]
 [17 14 20 28]]



In [24]:
costs = np.array( [[38, 43, 49, 21, 25, 26, 18, 49],
                   [32, 48, 34, 38, 29, 16, 45, 44],
                   [45, 16, 29, 25, 39, 29, 32, 34],
                   [44, 30, 41, 36, 27, 34, 33, 24],
                   [34, 43, 39, 10, 23, 17, 39, 23],
                   [26, 28, 36, 45, 27, 47, 36, 45],
                   [28, 22, 42, 10, 38, 19, 38, 25],
                   [19, 36, 21, 46, 13, 39, 30, 24]])

print("Matriu de costs:")
print(costs)
print()

# Millor solució trobada, cost: 154
# Tasca 0 -> Empresa 6
# Tasca 1 -> Empresa 5
# Tasca 2 -> Empresa 1
# Tasca 3 -> Empresa 7
# Tasca 4 -> Empresa 4
# Tasca 5 -> Empresa 0
# Tasca 6 -> Empresa 3
# Tasca 7 -> Empresa 2

tasks(costs)

Matriu de costs:
[[38 43 49 21 25 26 18 49]
 [32 48 34 38 29 16 45 44]
 [45 16 29 25 39 29 32 34]
 [44 30 41 36 27 34 33 24]
 [34 43 39 10 23 17 39 23]
 [26 28 36 45 27 47 36 45]
 [28 22 42 10 38 19 38 25]
 [19 36 21 46 13 39 30 24]]



En aquest cas no us podem donar la solució ja que és un exemple aleatori. Proveu-ho amb diferents mides de matrius.

In [25]:
costs = np.random.randint(10,50,(10,10))

print("Matriu de costs:")
print(costs)
print()

tasks(costs)

Matriu de costs:
[[17 17 28 46 12 27 33 26 24 31]
 [16 12 15 29 17 12 21 31 14 17]
 [38 17 31 10 34 13 43 44 12 27]
 [48 13 35 16 18 48 30 44 45 26]
 [37 11 20 47 27 13 35 15 43 12]
 [18 39 28 36 15 39 44 40 11 25]
 [17 44 41 11 31 45 34 35 10 17]
 [24 33 14 47 36 38 20 49 31 42]
 [22 22 27 40 19 39 41 17 34 45]
 [45 44 13 10 44 24 18 18 33 11]]

